

general.import = ["~/.cache/wal/colors-alacritty.toml"]
general.live_config_reload = true 



[window]

opacity = 0.9
blur=true

padding.x = 15
padding.y = 15

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "Caskaydia Cove Nerd Font Mono"
bold.family = "Caskaydia Cove Nerd Font Mono"
italic.family = "CodeNew Roman Nerd Font Mono"
bold_italic.family = "CodeNew Roman Nerd Font Mono"

size = 12.0


[selection]
save_to_clipboard = false

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
